clusterGroup:
    name: datacenter
    isHubCluster: true
  
    namespaces:
    - sepsis-demo
    - openshift-serverless
  
    subscriptions:
     amqstreams:
        name: amq-streams
        namespace: sepsis-demo
        channel: stable
     serverlessoperator:
        name: serverless-operator
        channel: stable
     rhsso-operator:  
        name: rhsso-operator
        channel: stable
        namespace: sepsis-demo
  
    projects:
    - sepsis-demo
  
    applications:
       sso:
         name: sso
         namespace: sepsis-demo
         project: sepsis-demo
         path: charts/all/sepsis-demo/sso
       kafka-cluster:
          name: kafka-cluster
          namespace: sepsis-demo
          project: sepsis-demo
          path: charts/all/sepsis-demo/kafka-cluster  
       fhir:
         name: fhir
         namespace: sepsis-demo
         project: sepsis-demo  
         path: charts/all/sepsis-demo/fhir-server
       debezium:
         name: debezium
         namespace: sepsis-demo
         project: sepsis-demo  
         path: charts/all/sepsis-demo/debezium
       kafdrop:
         name: kafdrop
         namespace: sepsis-demo
         project: sepsis-demo  
         path: charts/all/sepsis-demo/kafdrop
       knative-sepsis: 
         name: knative-sepsis
         namespace: sepsis-demo
         project: sepsis-demo  
         path: charts/all/sepsis-demo/knative
      
    imperative:
      image: quay.io/redhat_naps_da/ansible-execution-image-with-tools
      # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
      # The default schedule is every 10 minutes: imperative.schedule
      # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
      # imagePullPolicy is set to always: imperative.imagePullPolicy
      jobs:
      - name: sso-realm
        # ansible playbook to be run
        playbook: ansible/playbooks/sso-realm.yaml
        # per playbook timeout in seconds
        timeout: 234
        # verbosity: "-v"
  
    managedClusterGroups:
      region-one:
        name: region-one
        helmOverrides:
        - name: clusterGroup.isHubCluster
          value: false
        clusterSelector:
          matchLabels:
            clusterGroup: region-one
  
  #  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
  #
  #    pipelines:
  #      name: pipelines
  #      namespace: production
  #      project: datacenter
  #      path: applications/pipeline
  #      repoURL: https://github.com/you/applications.git
  #      targetRevision: stable
  #      overrides:
  #      - name: myparam
  #        value: myparam
  #
  #    pipelines_staging:
  #    - name: pipelines
  #      namespace: staging
  #      project: datacenter
  #      path: applications/pipeline
  #      repoURL: https://github.com/you/applications.git
  #      targetRevision: main
  #
  #   Additional applications
  #   Be sure to include additional resources your apps will require
  #   +X machines
  #   +Y RAM
  #   +Z CPU
  #    vendor-app:
  #      name: vendor-app
  #      namespace: default
  #      project: vendor
  #      path: path/to/myapp
  #      repoURL: https://github.com/vendor/applications.git
  #      targetRevision: main
  
  #  managedSites:
  #    factory:
  #      name: factory
  #      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
  #      targetRevision: main
  #      path: applications/factory
  #      helmOverrides:
  #      - name: site.isHubCluster
  #        value: false
  #      clusterSelector:
  #        matchExpressions:
  #        - key: vendor
  #          operator: In
  #          values:
  #            - OpenShift
  