kind: List
apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: {{ .Values.application_name }}
    name: {{ .Values.application_name }}
  spec:
    port:
      targetPort: http
    tls:
      termination: edge
    to:
      kind: Service
      name: {{ .Values.application_name }}
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Values.application_name }}
    labels:
      expose: "true"
      app: {{ .Values.application_name }}
  spec:
    ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 9000
    selector:
      group: kafdrop
      app: {{ .Values.application_name }}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: {{ .Values.application_name }}
    name: {{ .Values.application_name }}
  spec:
    replicas: 1
    selector:
      group: kafdrop
      app: {{ .Values.application_name }}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 3600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          group: kafdrop
          app: {{ .Values.application_name }}
      spec:
        containers:
          - image: {{ .Values.image_name }}:{{ .Values.image_tag }}
            name: {{ .Values.application_name }}
            ports:
            - containerPort: 9000
            env:
              - name: KAFKA_BROKERCONNECT
                value: {{ .Values.kafka_bootstrap_address }}
              - name: JVM_OPTS
                value: "-Xms32M -Xmx64M"
              - name: SERVER_SERVLET_CONTEXTPATH
                value: "/"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default
        serviceAccountName: default
        terminationGracePeriodSeconds: 30
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - {{ .Values.application_name }}
          from:
            kind: ImageStreamTag
            name: "{{ .Values.application_name }}:{{ .Values.image_tag }}"
        type: ImageChange
              
