namespace: sepsis-demo
plsql:
  psql_app_name: psql-fhir
  psql_credentials_secret: psql-secret
  postgresql_pv_capacity: 5Gi
  postgresql_service_account: fhir-service-user
  psql_port: 5432
  psql_user_name: fhir
  psql_user_passwd: fhir
  psql_db_name: fhir

configmap:
  postgres_configmap:
    name : fhir-postgres-cm
    create_db_file: sql/create_database.sh
    wait_for_psql_file: sql/wait_for_postgresql.sh
  debezium_configmap:
    name : fhir-debezium-cm  
    d_conf_file: sql/hapi-psql-debezium-conf.conf