apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: psql-fhir
    app.kubernetes.io/part-of: datatier
    argocd.argoproj.io/instance: fhir
  name: psql-fhir
  namespace: sepsis-demo
spec:
  replicas: 1
  selector:
    name: psql-fhir
  strategy:
    recreateParams:
      post:
        execNewPod:
          command:
            - /bin/bash
            - /tmp/init-files/wait_for_postgresql.sh
            - /tmp/init-files/create_database.sh
          containerName: postgresql
          volumes:
            - init-volume
        failurePolicy: Abort
      timeoutSeconds: 30
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: psql-fhir
        name: psql-fhir
    spec:
      containers:
        - capabilities: '{}'
          env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: admin
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: psql-fhir
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: psql-fhir
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: psql-fhir
            - name: POSTGRESQL_SERVICE
              value: psql-fhir
            - name: POSTGRESQL_MAX_PREPARED_TRANSACTIONS
              value: '100'
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: '100'
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
          name: postgresql
          ports:
            - containerPort: 5432
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - psql -h 127.0.0.1 -U fhir -q -d fhir -c 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: psql-fhir-data
            - mountPath: /tmp/init-files
              name: init-volume
            - mountPath: /opt/app-root/src/postgresql-cfg/
              name: fhir-debezium-cm
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: fhir-service-user
      volumes:
        - name: psql-fhir-data
          persistentVolumeClaim:
            claimName: psql-fhir
        - configMap:
            defaultMode: 493
            name: fhir-postgres-cm
          name: init-volume
        - configMap:
            defaultMode: 493
            name: fhir-debezium-cm
          name: fhir-debezium-cm
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - postgresql
        from:
          kind: ImageStreamTag
          name: 'postgresql:12-el8'
          namespace: sepsis-demo
        lastTriggeredImage: ''
      type: ImageChange
    - type: ConfigChange
