---

kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: {{ .Values.application_name }}
      expose: "true"
    name: {{ .Values.application_name }}
  spec:
    ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      group: fhir-server
      app: {{ .Values.application_name }}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: {{ .Values.application_name }}
    name: {{ .Values.application_name }}
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      group: fhir-server
      app: {{ .Values.application_name }}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 3600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          group: fhir-server
          app: {{ .Values.application_name }}
      spec:
        containers:
          - env:
            - name: JAVA_MAX_MEM_RATIO
              value: "{{ .Values.sepsisdetection_rhpam_java_max_mem_ratio }}"
            - name: JAVA_INITIAL_MEM_RATIO
              value: "{{ .Values.sepsisdetection_rhpam_java_initial_mem_ratio }}"
            - name: GC_MAX_METASPACE_SIZE
              value: "{{ .Values.sepsisdetection_rhpam_gc_max_metaspace_size }}"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: SPRING_CONFIG_LOCATION
              value: file:///deployments/config/{{ .Values.application_configmap_key }}

            # org.kie.server.repo: dictates to kie-server where to find its KIE container configuration file
            # kie.maven.settings.custom: dictates to kie-server where to fine its artifact repo of KJars
            - name: JAVA_OPTS_APPEND
              value: '-Dorg.kie.server.repo={{ .Values.kie_server_repo_path }} -Dkie.maven.settings.custom=/m2/settings.xml'

            - name: MAVEN_MIRROR_URL
              value: "{{ .Values.nexus_mirror }}"
            imagePullPolicy: IfNotPresent
            name: {{ .Values.application_name }}
            livenessProbe:
              failureThreshold: 3
              exec:
                command:
                - "/bin/bash"
                - "-c"
                - "curl --fail --silent -u '{{ .Values.kie_admin_user }}:{{ .Values.kie_admin_password }}' http://localhost:8080/rest/server/healthcheck"
              initialDelaySeconds: 30
              periodSeconds: 60
              timeoutSeconds: 3
            readinessProbe:
              failureThreshold: 3
              exec:
                command:
                - "/bin/bash"
                - "-c"
                - "curl --fail --silent -u '{{ .Values.kie_admin_user }}:{{ .Values.kie_admin_password }}' http://localhost:8080/rest/server/healthcheck"
              initialDelaySeconds: 30
              periodSeconds: 60
              timeoutSeconds: 3
            resources:
              limits:
                cpu: '1000m'
                memory: '2Gi'
              requests:
                cpu: '250m'
                memory: '250Mi'
            securityContext:
              privileged: false
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /deployments/config
              name: config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: {{ .Values.application_name }}
        serviceAccountName: {{ .Values.application_name }}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: {{ .Values.application_configmap_key }}
                path: {{ .Values.application_configmap_key }}
              - key: jbpm-quartz.properties
                path: jbpm-quartz.properties
              - key: logback-spring.xml
                path: logback-spring.xml
              - key: {{ .Values.application_name }}.xml
                path: {{ .Values.application_name }}.xml
            name: {{ .Values.application_configmap }}
          name: config
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - {{ .Values.application_name }}
          from:
            kind: ImageStreamTag
            name: "{{ .Values.application_name }}:{{ .Values.service_image_tag }}"
        type: ImageChange

