---
kind: List
apiVersion: v1
namespace: {{.Values.namespace}} 
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
        name: "{{ .Values.service_account }}"
        namespace: "{{ .Values.namespace }}" 

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
        name: "{{ .Values.service_account }}-admin"
        namespace: "{{ .Values.namespace }}"
    roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
    subjects:
    - kind: ServiceAccount
      name: "{{ .Values.service_account }}-admin"
      namespace: "{{ .Values.namespace }}"      


  - apiVersion: v1
    kind: ConfigMap
    metadata:
        name: "{{ .Values.application_configmap }}"
    data:
        application.properties: |-
          {{ range $lines := .Files.Lines .Values.configmap.application_configmap.application }}
             {{-  tpl $lines $ | trim }} 
          {{ end }}
        jbpm-quartz.properties: |-
          {{ range $lines := .Files.Lines .Values.configmap.application_configmap.jbpm_quartz }}
             {{- tpl $lines $ | trim }} 
          {{ end }}
        logback-spring.xml: |-
          {{ range $lines := .Files.Lines .Values.configmap.application_configmap.logback_spring }}
             {{- tpl $lines $ | trim }} 
          {{ end }}
        sepsisdetection-rhpam.xml: |-
          {{ range $lines := .Files.Lines .Values.configmap.application_configmap.sepsisdetection_rhpam }}
             {{- tpl $lines $ | trim }} 
          {{ end }}
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
        name: {{ .Values.application_name }}
        labels:
            app: {{ .Values.application_name }}
    spec:
        dockerImageRepository: {{ .Values.service_image }}

 