apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.application_name }}
spec:
  host: {{ .Values.application_name }}-{{ .Values.namespace }}.{{ .Values.global.hubClusterDomain }}
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Values.application_name }}
  wildcardPolicy: None
