kind: List
apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: {{ .Values.application_name }}
    name: {{ .Values.application_name }}
  spec:
    port:
      targetPort: http
    tls:
      termination: edge
    to:
      kind: Service
      name: {{ .Values.application_name }}
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Values.application_name }}
    labels:
      expose: "true"
      app: {{ .Values.application_name }}
  spec:
    ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 7080
    selector:
      group: sepsisdetection
      app: {{ .Values.application_name }}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: {{ .Values.application_name }}
    name: {{ .Values.application_name }}
  spec:
    replicas: 1
    selector:
      group: sepsisdetection
      app: {{ .Values.application_name }}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 3600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          group: sepsisdetection
          app: {{ .Values.application_name }}
      spec:
        containers:
          - image: {{ .Values.image_name }}:{{ .Values.image_tag }}
            name: {{ .Values.application_name }}
            ports:
            - containerPort: 7080
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 7080
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 3
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 7080
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 3
            resources:
              limits:
                memory: "1Gi"
                cpu: "500m"
            volumeMounts:
            - name: env
              mountPath: /opt/app-root/src/assets/js/env.js
              subPath: env.js
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: {{ .Values.application_name }}
        serviceAccountName: {{ .Values.application_name }}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            name: {{ .Values.application_name }}
          name: env
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - {{ .Values.application_name }}
          from:
            kind: ImageStreamTag
            name: "{{ .Values.application_name }}:{{ .Values.image_tag }}"
        type: ImageChange
