---
kind: List
apiVersion: v1
namespace: {{.Values.namespace}} 
items:
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ .Values.application_name }}"
        namespace: "{{ .Values.namespace }}"

    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ .Values.application_name }}"
      data:
        env.js: |-
            {{ range $lines := .Files.Lines .Values.configmap.envjs }}
              {{- $record :=   tpl $lines $ -}}
              {{- trim $record | indent 6 }}
            {{ end }}


    - apiVersion: image.openshift.io/v1
      kind: ImageStream
      metadata:
          name: {{ .Values.application_name }}
          labels:
             app: {{ .Values.application_name }}
      spec:
          dockerImageRepository: {{ .Values.image_name }}  