kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sso
  labels:
    app: keycloak
  annotations:
    openshift.io/host.generated: 'true'
  namespace: {{.Values.namespace}}  
spec:
  to:
    kind: Service
    name: keycloak
    weight: 100
  port:
    targetPort: keycloak
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None