---
kind: List
apiVersion: v1
namespace: {{.Values.namespace}} 
items:
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
       name: {{ .Values.fhirserver.applicationname }}

  - kind: RoleBinding     
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
        name: {{ printf "%s-admin" .Values.fhirserver.applicationname }}
    roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
    subjects:
      - kind: ServiceAccount
        name: {{ printf "%s-admin" .Values.fhirserver.applicationname }}
        namespace: {{.Values.namespace}}    

  - kind: ConfigMap
    apiVersion: v1
    metadata:
        name: {{ .Values.fhirserver.configmap.name }}
    data:
      application.yaml: |-
        {{ range $lines := .Files.Lines .Values.fhirserver.configmap.application_file }}
            {{- tpl $lines $ }} 
        {{ end }}
      value: {{.Values.global.hubClusterDomain}}    