---
kind: List
apiVersion: v1
namespace: {{.Values.namespace}} 
items:
 - kind: PersistentVolumeClaim
   apiVersion: v1
   metadata:
    name: {{.Values.plsql.psql_app_name}}
    labels:
      app: {{.Values.plsql.psql_app_name}}
     
   spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.plsql.postgresql_pv_capacity }}

 - kind: ServiceAccount       
   apiVersion: v1
   metadata:
        name: {{ .Values.plsql.postgresql_service_account }}
   labels:
      app: {{.Values.plsql.psql_app_name}}      

 - kind: ConfigMap     
   apiVersion: v1
   metadata:
      name: {{ .Values.configmap.postgres_configmap.name  }}
   labels:
      app: {{.Values.plsql.psql_app_name}}   
   data:
      create_database.sh: |-
        {{ range .Files.Lines .Values.configmap.postgres_configmap.create_db_file }}
            {{ . }}
        {{ end }}
      wait_for_postgresql.sh: |-   
        {{ range .Files.Lines .Values.configmap.postgres_configmap.wait_for_psql_file }}
            {{ . }}
        {{ end }}